server:
  port: 8090
#  use-forward-headers: true
#  undertow:
#    io-threads: 2
#    worker-threads: 36
#    buffer-size: 1024
#    directBuffers: true
  servlet:
    session:
      timeout: 86400s

spring:
  application:
    name: halo
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.104.236.138:3306/halodb?useUnicode=true&characterEncoding=utf8
    username: root
    password: www.123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  freemarker:
    allow-request-override: false
    cache: false
    check-template-location: true
    charset: utf-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    suffix: .ftl
    settings:
      auto_import: /spring.ftl as spring
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  # 多语言资源文件路径
  messages:
    basename: i18n/messages
logging:
  file: ./logs/log.log


